### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hohlick** [ImkeF/M-Guide#1]
in https://github.com/ImkeF/Caveats-in-native-M-functions/blob/master/Number.Mod/README.md the link to the Number.ModX.pq is broken.
Correct link:
https://github.com/ImkeF/Caveats-in-native-M-functions/blob/master/Number.Mod/Number.ModX.pq

**Comment by ImkeF** [comment]
Thanks Maxim! 
Fixed it :-)
